FROM apache/superset:latest

USER root

# Cài Snowflake + khóa dependency tương thích Superset
RUN /app/.venv/bin/python -m ensurepip --upgrade && \
    /app/.venv/bin/python -m pip install --no-cache-dir \
        snowflake-sqlalchemy\
        snowflake-connector-python\
        "cryptography" \
        "greenlet"

USER superset
